"""
ArthoSense NER - Regional Localization Module
Provides comprehensive multi-language dictionaries for North East Region field deployment.
Languages supported: English, Assamese (অসমীয়া), Khasi (Ka Ktien Khasi), 
Manipuri (মৈতৈলোন্ / Meiteilon), Mizo, Bodo, Hindi.
"""

TRANSLATIONS = {
    "English": {
        "app_title": "ArthoSense NER: Multimodal Knee OA Screening",
        "app_subtitle": "Offline-First Clinical Expert System & Early Detection Tool for the North East Region",
        "offline_badge": "🟢 100% Offline Edge Mode",
        "lang_select": "Regional Language",
        "nav_intake": "📋 Patient Intake & Questionnaire",
        "nav_screening": "🎥 Multimodal Screening (Vision + Sensors)",
        "nav_diagnosis": "🩺 Clinical Diagnosis & AI Report",
        "nav_records": "🗄️ Patient Records & Sync",
        "nav_evidence": "📊 Regional Evidence & ML Insights",
        "nav_hardware": "⚙️ Hardware Diagnostics",
        
        # Intake Form
        "patient_demographics": "Patient Demographics",
        "patient_name": "Full Name",
        "patient_age": "Age (years)",
        "patient_gender": "Gender",
        "male": "Male",
        "female": "Female",
        "other": "Other",
        "height_cm": "Height (cm)",
        "weight_kg": "Weight (kg)",
        "bmi_calc": "Calculated BMI",
        "district": "District / State",
        
        # Risk Factors
        "clinical_questions": "Epidemiological Risk Factors & Symptoms",
        "menopause_q": "Have you attained menopause? (For female patients)",
        "injury_q": "History of previous knee trauma or injury?",
        "family_history_q": "Family history of Knee Osteoarthritis?",
        "physical_activity": "Daily Physical Activity Level",
        "activity_sedentary": "Sedentary (Little to no exercise)",
        "activity_moderate": "Moderate (Regular walking/chores)",
        "activity_active": "Active (Regular sports/heavy work)",
        "occupation_loading": "Occupational Knee Loading (e.g., Tea-garden work, prolonged squatting, sloping terrain, heavy lifting)",
        "pain_score": "Knee Pain Severity (VAS 0–10)",
        "pain_desc": "0 = No Pain, 10 = Worst Possible Pain",
        "stiffness_q": "Morning joint stiffness lasting > 30 minutes?",
        "crepitus_q": "Audible or palpable clicking, grinding, or popping sounds during movement?",
        
        # Multimodal
        "vision_module": "Computer Vision Kinematics (Webcam + MediaPipe)",
        "sensor_module": "Wearable Sensor Stream (MPU6050 IMU + Piezo Acoustic Mic)",
        "rom_angle": "Knee Range of Motion (ROM Flexion Angle)",
        "vibration_rms": "Acoustic Crepitus RMS Vibration",
        "sensor_status": "Sensor Status",
        "start_camera": "Start Live Camera Kinematic Capture",
        "stop_camera": "Stop Camera Capture",
        "simulate_sensors": "Simulate Live Sensor Input (Field Testing Mode)",
        "connect_hardware": "Connect Physical Hardware (COM / BLE)",
        
        # Results & Diagnostic
        "clinical_result": "Screening Results & Clinical Severity",
        "rule_risk_title": "Evidence-Informed Rule Risk Score",
        "ml_risk_title": "Supervised ML Predicted Probability",
        "risk_low": "Low Risk (Grade 0: Normal / Healthy)",
        "risk_moderate": "Moderate Risk (Grade 1–2: Mild to Moderate OA)",
        "risk_high": "High Risk (Grade 3: Advanced OA / Severe)",
        "clinical_rationale": "Explainable Clinical Breakdown",
        "recommendations": "Actionable Clinical Pathway & Recommendations",
        "rec_low": "Maintain healthy weight, low-impact exercise (walking, swimming), monitor annually at village Sub-Center.",
        "rec_moderate": "Initiate quadriceps strengthening physiotherapy, ergonomic adjustments (reduce prolonged squatting/tea-garden heavy loads), follow-up at Primary Health Centre (PHC).",
        "rec_high": "Urgent referral to District Hospital / Orthopedic Specialist for clinical evaluation, radiographic imaging (X-Ray), and pharmacotherapy / joint management.",
        
        # Buttons & Actions
        "btn_run_screening": "Run Complete Multimodal Assessment",
        "btn_save_db": "Save Record to Local Database (arthosense.db)",
        "btn_download_report": "Generate Digital Clinical Report Card (PDF)",
        "btn_export_csv": "Export Records to CSV (Offline USB Sync)",
        "btn_export_json": "Export Records to JSON",
        "save_success": "Patient screening record successfully saved to local SQLite database!",
        "records_count": "Total Patients Screened Offline"
    },

    "Assamese": {
        "app_title": "আৰ্থ'চেন্স উত্তৰ-পূব: আঁঠুৰ বাতবিষ পৰীক্ষণ ব্যৱস্থা",
        "app_subtitle": "উত্তৰ-পূৰ্বাঞ্চলৰ গ্ৰাম্য স্বাস্থ্যকৰ্মীসকলৰ বাবে অফলাইন মাল্টিমোডেল স্ক্ৰীনিং সঁজুলি",
        "offline_badge": "🟢 ১০০% অফলাইন ব্যৱস্থা",
        "lang_select": "ভাষা নিৰ্বাচন কৰক",
        "nav_intake": "📋 ৰোগীৰ তথ্য আৰু প্ৰশ্নাৱলী",
        "nav_screening": "🎥 মাল্টিমোডেল পৰীক্ষণ (কেমেৰা + চেন্সৰ)",
        "nav_diagnosis": "🩺 ক্লিনিকেল নিদান আৰু এআই প্ৰতিবেদন",
        "nav_records": "🗄️ স্থানীয় ৰেকৰ্ড আৰু সংমিশ্ৰণ",
        "nav_evidence": "📊 আঞ্চলিক গৱেষণা আৰু প্ৰমাণ",
        "nav_hardware": "⚙️ হাৰ্ডৱেৰ পৰীক্ষা",
        
        # Intake Form
        "patient_demographics": "ৰোগীৰ ব্যক্তিগত তথ্য",
        "patient_name": "সম্পূৰ্ণ নাম",
        "patient_age": "বয়স (বছৰ)",
        "patient_gender": "লিংগ",
        "male": "পুৰুষ",
        "female": "মহিলা",
        "other": "অন্যান্য",
        "height_cm": "উচ্চতা (ছে.মি.)",
        "weight_kg": "ওজন (কে.জি.)",
        "bmi_calc": "বি.এম.আই. (BMI)",
        "district": "জিলা / ৰাজ্য",
        
        # Risk Factors
        "clinical_questions": "ৰোগৰ সম্ভাৱ্য কাৰক আৰু লক্ষণসমূহ",
        "menopause_q": "ৰজোনিবৃত্তি (Menopause) হৈছে নেকি? (মহিলাৰ বাবে)",
        "injury_q": "পূৰ্বে আঁঠুত কোনো আঘাত বা দুৰ্ঘটনা পাইছিল নেকি?",
        "family_history_q": "পৰিয়ালত কাৰোবাৰ আঁঠুৰ বাতবিষ আছিল নেকি?",
        "physical_activity": "দৈনন্দিন শাৰীৰিক কাম-কাজৰ মাত্ৰা",
        "activity_sedentary": "কম সক্ৰিয় (শাৰীৰিক পৰিশ্ৰম নাই)",
        "activity_moderate": "মধ্যমীয়া (দৈনন্দিন খোজকঢ়া/ঘৰৰ কাম)",
        "activity_active": "অধিক সক্ৰিয় (কঠিন পৰিশ্ৰম বা খেল-ধেমালি)",
        "occupation_loading": "কঠিন শ্ৰমিকৰ কাম (যেনে চাহ বাগিচাৰ কাম, অধিক সময় বহি থকা, পাহাৰীয়া ঢালত খোজকঢ়া, গধুৰ বস্তু কঢ়িওৱা)",
        "pain_score": "আঁঠুৰ বিষৰ মাত্ৰা (০ পৰা ১০)",
        "pain_desc": "০ = কোনো বিষ নাই, ১০ = অতি অসহ্যকৰ বিষ",
        "stiffness_q": "ৰাতিপুৱা শুই উঠাৰ পিছত আঁঠু ৩০ মিনিটতকৈ বেছি টান লাগি থাকে নেকি?",
        "crepitus_q": "খোজ কাঢ়োঁতে আঁঠুত কোনো শব্দ বা মৰমৰণি (Cracking/Grinding) অনুভৱ হয় নেকি?",
        
        # Multimodal
        "vision_module": "কম্পিউটাৰ ভিজন (ৱেবকেম + মিডিয়া পাইপ)",
        "sensor_module": "ৱেৰেবল চেন্সৰ (MPU6050 IMU + পিজো মাইক্ৰ'ফোন)",
        "rom_angle": "আঁঠু ভাঁজ কৰাৰ কোণ (Range of Motion)",
        "vibration_rms": "আঁঠুৰ কম্পনৰ মাত্ৰা (RMS Vibration)",
        "sensor_status": "চেন্সৰ অৱস্থা",
        "start_camera": "কেমেৰা পৰীক্ষণ আৰম্ভ কৰক",
        "stop_camera": "কেমেৰা বন্ধ কৰক",
        "simulate_sensors": "চেন্সৰ চিমুলেচন চলাওক (পৰীক্ষাৰ বাবে)",
        "connect_hardware": "হাৰ্ডৱেৰ সংযোগ কৰক (COM / BLE)",
        
        # Results & Diagnostic
        "clinical_result": "স্ক্ৰীনিং ফলাফল আৰু ক্লিনিকেল স্থিতি",
        "rule_risk_title": "প্ৰমাণ-ভিত্তিক নিয়মৰ বিপদ স্ক'ৰ",
        "ml_risk_title": "মেচিন লাৰ্নিং (ML) সম্ভাৱিতা",
        "risk_low": "কম আশংকা (গ্ৰেড ০: স্বাভাৱিক / সুস্থ)",
        "risk_moderate": "মধ্যমীয়া আশংকা (গ্ৰেড ১–২: প্ৰাৰম্ভিক বাতবিষ)",
        "risk_high": "অধিক আশংকা (গ্ৰেড ৩: গুৰুতৰ বাতবিষ)",
        "clinical_rationale": "ক্লিনিকেল ব্যাখ্যা আৰু কাৰণ",
        "recommendations": "স্বাস্থ্য পৰামৰ্শ আৰু চিকিৎসাৰ নিৰ্দেশনা",
        "rec_low": "ওজন নিয়ন্ত্ৰণত ৰাখক, নিয়মীয়াকৈ খোজ কাঢ়ক, গাঁৱৰ উপ-স্বাস্থ্য কেন্দ্ৰত বছৰেকীয়া পৰীক্ষা কৰাওক।",
        "rec_moderate": "আঁঠু মজবুত কৰা ব্যায়াম (ফিজিঅ'থেৰাপী) কৰক, চাহ বাগিচাত দীৰ্ঘ সময় বহি কাম কৰা হ্ৰাস কৰক, প্ৰাথমিক স্বাস্থ্য কেন্দ্ৰত (PHC) দেখুৱাওক।",
        "rec_high": "অবিলম্বে জিলা চিকিৎসালয় বা অস্থিৰোগ বিশেষজ্ঞৰ (Orthopedic) ওচৰলৈ গৈ এক্স-ৰে (X-Ray) আৰু চিকিৎসা গ্ৰহণ কৰক।",
        
        # Buttons & Actions
        "btn_run_screening": "সম্পূৰ্ণ পৰীক্ষণ সম্পন্ন কৰক",
        "btn_save_db": "স্থানীয় ডেটাবেচত সংৰক্ষণ কৰক",
        "btn_download_report": "ডিজিটেল প্ৰতিবেদন ডাউনলোড কৰক (PDF)",
        "btn_export_csv": "CSV ফাইলেৰে ডাটা এক্সপ'ৰ্ট কৰক (USB Sync)",
        "btn_export_json": "JSON এক্সপ'ৰ্ট",
        "save_success": "ৰোগীৰ পৰীক্ষণ ফলাফল স্থানীয় SQLite ডেটাবেচত সফলতাৰে সংৰক্ষিত হ'ল!",
        "records_count": "অফলাইন পৰীক্ষা কৰা মুঠ ৰোগীৰ সংখ্যা"
    },

    "Khasi": {
        "app_title": "ArthoSense NER: Ka Jingpeit Bniah ia ka Khrew Khohsiew",
        "app_subtitle": "Ka kor ai jingsumar khlem internet na ka bynta ki nongtrei ka koit ka khiah ha ki thaiñ nongkyndong",
        "offline_badge": "🟢 100% Khlem Internet (Offline)",
        "lang_select": "Jied ia ka Ktien",
        "nav_intake": "📋 Jingtip u Nongpang & Jingkylli",
        "nav_screening": "🎥 Ka Jingpeit Bniah (Camera + Sensor)",
        "nav_diagnosis": "🩺 Ka jingbatai & AI Kaiphod",
        "nav_records": "🗄️ Ki Record & Ka Jingkynshew",
        "nav_evidence": "📊 Ki Jinglap & Statics",
        "nav_hardware": "⚙️ Ka Jingpeit ia ki Tiang Hardware",
        
        "patient_demographics": "Jingtip Shaphang u Nongpang",
        "patient_name": "Kyrteng Bapura",
        "patient_age": "Rta (Snem)",
        "patient_gender": "Jait Shynrang/Kynthei",
        "male": "Shynrang",
        "female": "Kynthei",
        "other": "Kawei pat",
        "height_cm": "Jingjrong (cm)",
        "weight_kg": "Jingkhia (kg)",
        "bmi_calc": "BMI",
        "district": "Distrik / Jylla",
        
        "clinical_questions": "Ki Jingkylli halor ka Jingpang Khohsiew",
        "menopause_q": "La poi ha ka rta ba la sangeh bnai? (Na ka bynta ki kynthei)",
        "injury_q": "Mynshuwa ju mynsaw ne mong ha ka khohsiew?",
        "family_history_q": "Don ha iing ba don jingpang khrew khohsiew?",
        "physical_activity": "Ka jingtrei kam man ka sngi",
        "activity_sedentary": "Khlem da don jingkhih kynroi",
        "activity_moderate": "Gait/iaid beit man ka sngi",
        "activity_active": "Kiba trei shitom/kiba iaid khyndew eh",
        "occupation_loading": "Ka kam ba don jingtrei shitom ha khohsiew (Kiba shong khop, kiba kit jingkhia, kiba trei lyngkha/shyiap)",
        "pain_score": "Ka jingpang ha ka khohsiew (0–10)",
        "pain_desc": "0 = Em shym pang, 10 = Pang jur eh",
        "stiffness_q": "Ha ka step ka khohsiew ka eh palat 30 minit?",
        "crepitus_q": "Don jingriew kynshok/krih haba iaid ne khun khohsiew?",
        
        "vision_module": "Computer Vision (MediaPipe Camera)",
        "sensor_module": "Sensor ba deng (IMU + Piezo)",
        "rom_angle": "Ka jinglah ban khun ia ka khohsiew (ROM)",
        "vibration_rms": "Ka jingkhih puid jong ka khohsiew (RMS)",
        "sensor_status": "Sensor Status",
        "start_camera": "Plie ia ka Camera",
        "stop_camera": "Khnang ia ka Camera",
        "simulate_sensors": "Pyndonkam Simulator (Testing)",
        "connect_hardware": "Pyniasoh Hardware (COM / BLE)",
        
        "clinical_result": "Ka Jingbatai halor ka Koit ka Khiah",
        "rule_risk_title": "Ka Jingñiew Jingma (Evidence-Based Rule)",
        "ml_risk_title": "Machine Learning (ML Probability)",
        "risk_low": "Duna ka Jingma (Grade 0: Bha / Koit)",
        "risk_moderate": "Shiteng ka Jingma (Grade 1-2: Pyrshang Khrew)",
        "risk_high": "Jingma kaba Khraw (Grade 3: Khrew Jur)",
        "clinical_rationale": "Ka Daw & Jingbatai Bniah",
        "recommendations": "Ki lad ban pynbha & Jingsumar",
        "rec_low": "Pynneh ia ka jingkhia ba biang, iaid beit man ka sngi, jurip ha Sub-Centre shisien shisnem.",
        "rec_moderate": "Leh ki exercise ban pynkhlaiñ ia ki dohksah khohsiew (physiotherapy), leit sha PHC ban ioh jingsumar.",
        "rec_high": "Leit kloi sha District Hospital ne sha u Doctor Khohsiew (Orthopedic) ban shon X-Ray bad ioh jingsumar.",
        
        "btn_run_screening": "Pynurlong ia ka Jingpeit Bniah",
        "btn_save_db": "Kynshew ha SQLite Database",
        "btn_download_report": "Siew / Download Kaiphod (PDF)",
        "btn_export_csv": "Export sha CSV (USB Sync)",
        "btn_export_json": "Export sha JSON",
        "save_success": "La kynshew pura ia ka record ha ka Local Database!",
        "records_count": "Kiba la dep peit bniah baroh"
    },

    "Manipuri": {
        "app_title": "ArthoSense NER: খুউগী ওষ্টিওআৰ্থ্ৰাইটিছ চাংয়েং",
        "app_subtitle": "নোংপোক-চীংগী লমদমগীদমক অফলাইন মল্টিমোডেল স্ক্রীনিং খুৎলায়",
        "offline_badge": "🟢 ১০০% অফলাইন",
        "lang_select": "লোল খনবীয়ু",
        "nav_intake": "📋 অনাবগী ৱাফম & ৱাহং",
        "nav_screening": "🎥 মল্টিমোডেল চাংয়েং (কেমেরা + সেন্সর)",
        "nav_diagnosis": "🩺 ক্লিনিকাল ৱারেপ & AI রিপোর্ট",
        "nav_records": "🗄️ রিকোর্দশিং & সিংক",
        "nav_evidence": "📊 থিজিনবা & প্রমান",
        "nav_hardware": "⚙️ হার্দৱেয়র ডায়াগ্নোষ্টিক",
        
        "patient_demographics": "অনাবগী ই-পাউ",
        "patient_name": "মমিং",
        "patient_age": "চহী",
        "patient_gender": "লৈনঙ",
        "male": "নুপা",
        "female": "নুপী",
        "other": "অতোপ্পা",
        "height_cm": "অৱাংবা (cm)",
        "weight_kg": "লুম্বা (kg)",
        "bmi_calc": "BMI",
        "district": "জিলা / রাজ্য",
        
        "clinical_questions": "খুউ অনাবগী মরুওইবা ৱাফমশিং",
        "menopause_q": "মেনোপোজ (Menopause) ওইখ্রবরা? (নুপীগীদমক)",
        "injury_q": "হান্না খুউদা অশোক-অপন নংখিবরা?",
        "family_history_q": "ইমুংদা খুউগী বাত অনাবা লৈবরা?",
        "physical_activity": "নুমিৎ খুদিংগী হকচাংগী এক্টিভিটি",
        "activity_sedentary": "এক্টিভিটি য়াম্না তৌদবা",
        "activity_moderate": "চম্পা খোঙচৎ/য়ুমগী থবক",
        "activity_active": "য়াম্না কনবা শিন-থবক",
        "occupation_loading": "খুউদা লুনা তাবা থবক (চিংশাংদা চৎপা, চাগুজাগা তৌবা, লুম্বা পুবা)",
        "pain_score": "খুউ অনাবগী চাং (০-১০)",
        "pain_desc": "০ = অনা লৈতে, ১০ = য়াম্না চাউনা অনা",
        "stiffness_q": "অয়ুক হৌগৎপদা খুউ মিনিত ৩০ হেন্না চেৎনা লৈবরা?",
        "crepitus_q": "খুউ নোংমদা খোঞ্জেল (Cracking sound) থোকপ্ৰা?",
        
        "vision_module": "কম্পিউটার ভিজন (MediaPipe)",
        "sensor_module": "ৱেয়রেবল সেন্সর (IMU + Piezo)",
        "rom_angle": "খুউ ওনবগী চাং (ROM Angle)",
        "vibration_rms": "খুউগী ভাইব্রেশন (RMS Vibration)",
        "sensor_status": "সেন্সরগী ফিভম",
        "start_camera": "কেমেরা হৌদোকউ",
        "stop_camera": "কেমেরা থিংগৎলু",
        "simulate_sensors": "সিমুলেশন তৌউ",
        "connect_hardware": "হার্দৱেয়র কনেক্ট তৌউ",
        
        "clinical_result": "চাংয়েংগী মহৈ & ক্লিনিকাল গ্রেড",
        "rule_risk_title": "প্রমানদা য়ুম্ফম ওইবা রিস্ক স্কোর",
        "ml_risk_title": "মেশিন লার্নিং (ML) সম্ভব্যতা",
        "risk_low": "অশোকপা ৱাৎপা (Grade 0: অফবা / হকচাং ফবা)",
        "risk_moderate": "ময়াই ওইবা অশোকপা (Grade 1-2: বাতকী অহানবা তাঙ্কাক)",
        "risk_high": "য়াম্না চাউবা অশোকপা (Grade 3: গুৰুতৰ বাত)",
        "clinical_rationale": "ক্লিনিকাল এক্সপ্লেনেশন",
        "recommendations": "লায়েংবগী পাউতাক",
        "rec_low": "লুম্বা হন্থহনগদবনি, নুমিৎ খুদিংগী খোঙনা চৎকদবনি।",
        "rec_moderate": "খুউ ফহন্নবা ব্যায়াম (Physiotherapy) তৌগদবনি, PHC দা উৎলু।",
        "rec_high": "জিলা হাসপাতালদা চৎতুনা অর্থোপেডিক ডাক্তরদা উৎতুনা এক্স-রে তৌগদবনি।",
        
        "btn_run_screening": "চাংয়েং তৌবা হৌউ",
        "btn_save_db": "SQLite দা সেভ তৌউ",
        "btn_download_report": "রিপোর্ট দাউনলোড তৌউ (PDF)",
        "btn_export_csv": "CSV ফাইল এক্সপোর্ট তৌউ",
        "btn_export_json": "JSON এক্সপোর্ট",
        "save_success": "লোকেল ডাটাবেজদা সেভ তৌরে!",
        "records_count": "অপুনবা অনাবা স্ক্রিন তৌখিবা"
    },

    "Hindi": {
        "app_title": "ArthoSense NER: एआई-सक्षम घुटने के ऑस्टियोआर्थराइटिस की स्क्रीनिंग",
        "app_subtitle": "पूर्वोत्तर क्षेत्र के ग्रामीण स्वास्थ्य कार्यकर्ताओं के लिए 100% ऑफलाइन मल्टीमॉडल स्क्रीनिंग टूल",
        "offline_badge": "🟢 १००% ऑफलाइन मोड",
        "lang_select": "भाषा चुनें",
        "nav_intake": "📋 मरीज का विवरण और प्रश्नावली",
        "nav_screening": "🎥 मल्टीमॉडल स्क्रीनिंग (कैमरा + सेंसर)",
        "nav_diagnosis": "🩺 क्लिनिकल निदान और एआई रिपोर्ट",
        "nav_records": "🗄️ मरीज रिकॉर्ड और सिंक",
        "nav_evidence": "📊 क्षेत्रीय अनुसंधान एवं साक्ष्य",
        "nav_hardware": "⚙️ हार्डवेयर परीक्षण",
        
        "patient_demographics": "मरीज की सामान्य जानकारी",
        "patient_name": "पूरा नाम",
        "patient_age": "उम्र (वर्ष)",
        "patient_gender": "लिंग",
        "male": "पुरुष",
        "female": "महिला",
        "other": "अन्य",
        "height_cm": "कद (सें.मी.)",
        "weight_kg": "वजन (कि.ग्रा.)",
        "bmi_calc": "गणना किया गया बीएमआई (BMI)",
        "district": "जिला / राज्य",
        
        "clinical_questions": "महामारी विज्ञान जोखिम कारक और लक्षण",
        "menopause_q": "क्या रजोनिवृत्ति (Menopause) हो चुकी है? (महिला मरीजों के लिए)",
        "injury_q": "क्या पहले घुटने में कोई चोट या दुर्घटना हुई थी?",
        "family_history_q": "क्या परिवार में किसी को घुटने के गठिया की समस्या रही है?",
        "physical_activity": "दैनिक शारीरिक गतिविधि का स्तर",
        "activity_sedentary": "कम सक्रिय (व्यायाम नहीं)",
        "activity_moderate": "मध्यम (दैनिक पैदल चलना/घरेलू कार्य)",
        "activity_active": "अधिक सक्रिय (कठिन शारीरिक श्रम)",
        "occupation_loading": "व्यावसायिक घुटने का भार (जैसे चाय बागान कार्य, लंबे समय तक उकड़ू बैठना, ढलान पर चलना, वजन उठाना)",
        "pain_score": "घुटने के दर्द की गंभीरता (0–10)",
        "pain_desc": "0 = कोई दर्द नहीं, 10 = असहनीय तीव्र दर्द",
        "stiffness_q": "सुबह उठने के बाद घुटनों में 30 मिनट से अधिक जकड़न रहती है?",
        "crepitus_q": "घुटने को मोड़ने या चलने पर कट-कट या घिसने की आवाज (Crepitus) आती है?",
        
        "vision_module": "कंप्यूटर विजन किनेमैटिक्स (वेबकैम + मीडियापाइप)",
        "sensor_module": "वियरेबल सेंसर (MPU6050 IMU + पीजो माइक्रोफोन)",
        "rom_angle": "घुटने के मुड़ने का कोण (Range of Motion)",
        "vibration_rms": "घुटने के कंपन का स्तर (RMS Vibration)",
        "sensor_status": "सेंसर की स्थिति",
        "start_camera": "कैमरा स्क्रीनिंग शुरू करें",
        "stop_camera": "कैमरा बंद करें",
        "simulate_sensors": "सेंसर सिमुलेशन चलाएं (फील्ड टेस्टिंग)",
        "connect_hardware": "हार्डवेयर कनेक्ट करें (COM / BLE)",
        
        "clinical_result": "स्क्रीनिंग परिणाम और क्लिनिकल गंभीरता",
        "rule_risk_title": "साक्ष्य-आधारित नियम जोखिम स्कोर",
        "ml_risk_title": "मशीन लर्निंग (ML) अनुमानित प्रायिकता",
        "risk_low": "कम जोखिम (ग्रेड 0: सामान्य / स्वस्थ)",
        "risk_moderate": "मध्यम जोखिम (ग्रेड 1-2: प्रारंभिक गठिया)",
        "risk_high": "उच्च जोखिम (ग्रेड 3: गंभीर ऑस्टियोआर्थराइटिस)",
        "clinical_rationale": "पारदर्शी क्लिनिकल विवरण",
        "recommendations": "उपचार परामर्श और दिशा-निर्देश",
        "rec_low": "वजन नियंत्रित रखें, नियमित पैदल चलें, गांव के उप-स्वास्थ्य केंद्र पर वार्षिक जांच करवाएं।",
        "rec_moderate": "घुटने मजबूत करने वाले व्यायाम (फिजियोथेरेपी) करें, चाय बागान में लंबे समय तक उकड़ू बैठने से बचें, प्राथमिक स्वास्थ्य केंद्र (PHC) में दिखाएं।",
        "rec_high": "तत्काल जिला अस्पताल या आर्थोपेडिक विशेषज्ञ को दिखाकर एक्स-रे और उपचार शुरू करवाएं।",
        
        "btn_run_screening": "पूर्ण मल्टीमॉडल मूल्यांकन करें",
        "btn_save_db": "लोकल डेटाबेस में सहेजें (SQLite)",
        "btn_download_report": "डिजिटल मेडिकल रिपोर्ट कार्ड (PDF) डाउनलोड करें",
        "btn_export_csv": "CSV डेटा निर्यात करें (USB Sync)",
        "btn_export_json": "JSON निर्यात करें",
        "save_success": "मरीज का रिकॉर्ड सफलतापूर्वक स्थानीय SQLite डेटाबेस में सहेजा गया!",
        "records_count": "ऑफलाइन जांचे गए कुल मरीज"
    },

    "Mizo": {
        "app_title": "ArthoSense NER: Khup Ruhseh Endikna Khawl",
        "app_subtitle": "Internet ngai lo multimodal screening hmanraw tha North East tan",
        "offline_badge": "🟢 100% Offline",
        "lang_select": "Tawng thlan tur",
        "nav_intake": "📋 Damlo Chanchin & Zawhna",
        "nav_screening": "🎥 Multimodal Endikna (Camera + Sensor)",
        "nav_diagnosis": "🩺 Enchhanna & AI Report",
        "nav_records": "🗄️ Damlo Record & Sync",
        "nav_evidence": "📊 Zirchianna & Data",
        "nav_hardware": "⚙️ Hardware Endikna",
        
        "patient_demographics": "Damlo Chanchin Tlangpui",
        "patient_name": "Hming Pum",
        "patient_age": "Kum",
        "patient_gender": "Mipa/Hmeichhia",
        "male": "Mipa",
        "female": "Hmeichhia",
        "other": "Dang",
        "height_cm": "San zawng (cm)",
        "weight_kg": "Rih zawng (kg)",
        "bmi_calc": "BMI",
        "district": "District / State",
        
        "clinical_questions": "Khup Ruhseh Lanchhawn Theihte",
        "menopause_q": "Thla tin thi neih a tawp tawh em? (Hmeichhia tan)",
        "injury_q": "Hmanah khup ah hliam i tawk tawh em?",
        "family_history_q": "Chhungte khup ruhseh nei an awm em?",
        "physical_activity": "Nikhata taksa chet velna",
        "activity_sedentary": "Taksa che vak lo",
        "activity_moderate": "Kalo / In chhung hna thawk pangngai",
        "activity_active": "Hna rim thawk / Infiammi",
        "occupation_loading": "Khup tana hna hahthlak (Thingtlang hna, buk zual, chho-thlak kal rim)",
        "pain_score": "Khup na nat zawng (0–10)",
        "pain_desc": "0 = Na lo, 10 = Na lutuk",
        "stiffness_q": "Zing thawh rualin khup a khawng rei em (Minit 30 aia rei)?",
        "crepitus_q": "Kal / khup thlep zawngin ri (krih/khap) a awm em?",
        
        "vision_module": "Computer Vision (MediaPipe Camera)",
        "sensor_module": "Wearable Sensor (IMU + Piezo)",
        "rom_angle": "Khup thlep theih zawng (ROM)",
        "vibration_rms": "Khup chhung chetna (RMS Vibration)",
        "sensor_status": "Sensor Dinhmun",
        "start_camera": "Camera On rawh",
        "stop_camera": "Camera Off rawh",
        "simulate_sensors": "Sensor Simulation hman",
        "connect_hardware": "Hardware Zawmna (COM / BLE)",
        
        "clinical_result": "Endikna Hmuhchhuah & Dinhmun",
        "rule_risk_title": "Evidence-Based Risk Score",
        "ml_risk_title": "Machine Learning (ML Probability)",
        "risk_low": "Hlauhawm lo (Grade 0: Tha / Hrisel)",
        "risk_moderate": "Hlauhawm ve deuh (Grade 1-2: Ruhseh bul)",
        "risk_high": "Hlauhawm tak (Grade 3: Ruhseh Na)",
        "clinical_rationale": "A Chhan & Hrilhfiahna",
        "recommendations": "Inenkawl dan tur rawtna",
        "rec_low": "Rihna ti tlem la, nitin kal tam rawh, Sub-Centre ah in entir ziah rawh.",
        "rec_moderate": "Khup tihchakna exercise ti la, hna hah lutuk thawk lo la, PHC ah in entir rawh.",
        "rec_high": "District Hospital ah Doctor Specialist (Orthopedic) hnenah in entir vat la, X-Ray la rawh.",
        
        "btn_run_screening": "Endikna tan rawh",
        "btn_save_db": "SQLite ah vawng tha rawh",
        "btn_download_report": "Medical Report Download rawh (PDF)",
        "btn_export_csv": "CSV Export (USB Sync)",
        "btn_export_json": "JSON Export",
        "save_success": "Local Database ah hlawhtling takin a in save e!",
        "records_count": "Damlo endik tawh zat"
    },

    "Bodo": {
        "app_title": "ArthoSense NER: आरथ'चेन्स उत्तर-पूर्वाञ्चल",
        "app_subtitle": "गामियार देहा फाहामगिरिफोरनि थाखाय अफलाइन स्क्रिनिं आगजु",
        "offline_badge": "🟢 १००% अफलाइन",
        "lang_select": "राव सायख'",
        "nav_intake": "📋 सुंग्रानि खारि आरो सोंलु",
        "nav_screening": "🎥 मालटिम'डेल नायबिजिरनाय (केमेरा + चेनसर)",
        "nav_diagnosis": "🩺 क्लिनिकेल फिथाय आरो एआई रिपर्ट",
        "nav_records": "🗄️ सुंग्रानि फारिलाइ",
        "nav_evidence": "📊 आनजाद आरो गुदि खारि",
        "nav_hardware": "⚙️ हार्डवेयार आनजाद",
        
        "patient_demographics": "सुंग्रानि खारि",
        "patient_name": "गासै मुं",
        "patient_age": "बैसो (बोसोर)",
        "patient_gender": "लिंग'",
        "male": "हौवा",
        "female": "हिनजाव",
        "other": "गुबुन",
        "height_cm": "ज'थाइ (cm)",
        "weight_kg": "लिरथाइ (kg)",
        "bmi_calc": "BMI",
        "district": "जिला / हादोरसा",
        
        "clinical_questions": "खान्थि आरो लक्षणफोर",
        "menopause_q": "मेनोप'ज जाबाय नामा? (हिनजावफोरनि थाखाय)",
        "injury_q": "सिगां आथिंनि खन्थियाव आघात मोननाय दंमोन नामा?",
        "family_history_q": "नख'राव सोरनिबा खन्थिनि बात बेराम दंमोन नामा?",
        "physical_activity": "सानफ्रोमबोनि देहायारि हाबा",
        "activity_sedentary": "हाबा बारा गैया",
        "activity_moderate": "गेजेरारि (सानफ्रोमनि थाबायनाय)",
        "activity_active": "गोब्राब हाबा मावग्रा",
        "occupation_loading": "गोब्राब हाबा (साहा बागाननि हाबा, गोबाव जिरायनाय, लिरथाइ दैखांनाय)",
        "pain_score": "खन्थिनि सानाय (०-१०)",
        "pain_desc": "० = साया, १० = जोबोद सानाय",
        "stiffness_q": "फुङाव खन्थिया ३० मिनिटनिख्रुइ बांसिन गोजां जाना थायो नामा?",
        "crepitus_q": "थाबायब्ला खन्थियाव सोदोब (Cracking) ओंखारो नामा?",
        
        "vision_module": "कंप्युटार भिजन (MediaPipe)",
        "sensor_module": "चेनसर (IMU + Piezo)",
        "rom_angle": "खन्थि खन'नायनि खना (ROM)",
        "vibration_rms": "कम्पन (RMS Vibration)",
        "sensor_status": "चेनसरनि थासारि",
        "start_camera": "केमेरा जागाय",
        "stop_camera": "केमेरा बन्द खालाम",
        "simulate_sensors": "चेनसर सिमुलेसन",
        "connect_hardware": "हार्डवेयार फोनांजाब",
        
        "clinical_result": "नायबिजिरनाय फिथाय",
        "rule_risk_title": "गुदि-खारि आधारित खैफ'द",
        "ml_risk_title": "मेसिन लारनिं (ML) फिथाय",
        "risk_low": "खैफ'द गैयि (Grade 0: मोजां / देहा गोख्रों)",
        "risk_moderate": "गेजेरारि खैफ'द (Grade 1-2: गुदि बात)",
        "risk_high": "गोब्राब खैफ'द (Grade 3: गोब्राब बात)",
        "clinical_rationale": "क्लिनिकेल बेखेवनाय",
        "recommendations": "फाहामथायनि बुंफोरथि",
        "rec_low": "लिरथाइ खम खालाम, सानफ्रोम थाबाय, गामिनि साब-सेन्टाराव नायबिजिर।",
        "rec_moderate": "खन्थि गोग्गो खालामनो बियायाम खालाम (Physiotherapy), PHC आव थां।",
        "rec_high": "जिला देहा फाहामसालिनि डाक्टरनाव (Orthopedic) थांनानै एक्स-रे खालाम।",
        
        "btn_run_screening": "नायबिजिरनाय खालाम",
        "btn_save_db": "SQLite आव दोनथुम",
        "btn_download_report": "रिपर्ट दाउनल'ड (PDF)",
        "btn_export_csv": "CSV एक्सफ'र्ट (USB Sync)",
        "btn_export_json": "JSON एक्सफ'र्ट",
        "save_success": "मोजाङै दोनथुमबाय!",
        "records_count": "गासै नायबिजिरनाय सुब्रां"
    }
}

def get_text(key: str, lang: str = "English") -> str:
    """Helper to retrieve localized text string safely."""
    lang_dict = TRANSLATIONS.get(lang, TRANSLATIONS["English"])
    return lang_dict.get(key, TRANSLATIONS["English"].get(key, key))
